# Generated by Django 3.2 on 2021-05-21 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemSender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-date_sent',),
            },
        ),
        migrations.CreateModel(
            name='ItemReciever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=200)),
                ('address', models.CharField(max_length=150)),
                ('postal_code', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.itemsender')),
            ],
            options={
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='ItemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.CharField(max_length=150)),
                ('quantity', models.IntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('weight', models.CharField(max_length=10)),
                ('paid', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('sent', 'SENT'), ('delivered', 'DELIVERED')], default='PENDING', max_length=15)),
                ('problem_type', models.CharField(choices=[('paperwork', 'PAPERWORK_OVERLOAD'), ('custom_clerance', 'CUSTOM CLEARANCE'), ('bad weather', 'BAD WEATHER'), ('holidays', 'HOLYDAYS')], default='PENDING', max_length=15)),
                ('item_code', models.CharField(max_length=20)),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_recieved', models.DateTimeField(default=django.utils.timezone.now)),
                ('item_reciever', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.itemreciever')),
                ('item_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipment.itemsender')),
            ],
            options={
                'ordering': ('-date_sent', '-date_recieved'),
            },
        ),
    ]
