# Generated by Django 3.2 on 2021-05-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='food_photos'),
        ),
    ]
