# Generated by Django 3.2 on 2021-09-23 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0003_alter_itemdetail_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='problem_type',
            field=models.CharField(choices=[('no problem', 'No Problems'), ('paperwork', 'PAPERWORK_OVERLOAD'), ('custom clerance', 'CUSTOM CLEARANCE'), ('bad weather', 'BAD WEATHER'), ('holidays', 'HOLYDAYS')], default='NO PROBLEM', max_length=15),
        ),
    ]
