# Generated by Django 3.2 on 2021-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0004_alter_itemdetail_problem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='status',
            field=models.CharField(choices=[('pending', 'ON ROUTE'), ('sent', 'SENT'), ('delivered', 'DELIVERED')], default='PENDING', max_length=15),
        ),
    ]
