# Generated by Django 3.2 on 2021-11-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0005_alter_itemdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='package_photos'),
        ),
    ]
