# Generated by Django 3.2 on 2021-11-29 18:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0007_itemdetail_delivery_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 6, 18, 21, 52, 295122, tzinfo=utc)),
        ),
    ]
