# Generated by Django 3.2.9 on 2021-11-30 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0008_alter_itemdetail_delivery_frame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 7, 7, 35, 45, 92455, tzinfo=utc)),
        ),
    ]
