# Generated by Django 3.2.9 on 2021-12-09 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shipment', '0009_alter_itemdetail_delivery_frame'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemdetail',
            name='date_shipped',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 9, 25, 7, 209640, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='itemdetail',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='delivery_frame',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 16, 9, 25, 7, 210639, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='status',
            field=models.CharField(choices=[('transit', 'ON TRANSIT'), ('withheld', 'WITHHELD'), ('sent', 'SENT'), ('delivered', 'DELIVERED')], default='transit', max_length=15),
        ),
    ]
